# Generated by Django 3.2.3 on 2021-06-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_form_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form'),
        ),
    ]
