# Generated by Django 3.2.3 on 2021-05-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_choice_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
