# Generated by Django 3.2.3 on 2021-06-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selected_choice',
            name='choice_id',
        ),
        migrations.AddField(
            model_name='selected_choice',
            name='choice_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
