# Generated by Django 3.2.3 on 2021-05-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20210526_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_form_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
