# Generated by Django 3.2.3 on 2021-06-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20210616_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score_list',
            field=models.JSONField(default=list),
        ),
    ]
