# Generated by Django 3.2.3 on 2021-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_post_score_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
