# Generated by Django 3.1.3 on 2021-07-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('url', models.CharField(default='', max_length=1000)),
                ('price', models.CharField(max_length=200)),
                ('avg_rating', models.CharField(default='', max_length=200)),
                ('reviews_count', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
