# Generated by Django 3.1.3 on 2021-07-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('url', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('avg_rating', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('reviews_count', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
