export const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS'
export const GET_POST_LIST_FAIL = 'GET_POST_LIST_FAIL'

export const GET_POST_DETAIL_SUCCESS = 'GET_POST_DETAIL_SUCCESS'
export const GET_POST_DETAIL_FAIL = 'GET_POST_DETAIL_FAIL'

export const GET_USER_POST_SUCCESS = 'GET_USER_POST_SUCCESS'
export const GET_USER_POST_FAIL = 'GET_USER_POST_FAIL'

export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'

export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL'

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const POST_LOADING = 'POST_LOADING'
export const RESET_POST_LOADING = 'RESET_POST_LOADING'

export const RESET_POST_ERROR_MSG = 'RESET_POST_ERROR_MSG'

export const RESET_CREATE_POST_SUCCESS = 'RESET_CREATE_POST_SUCCESS'
export const RESET_EDIT_POST_SUCCESS = 'RESET_EDIT_POST_SUCCESS'
export const RESET_DELETE_POST_SUCCESS = 'RESET_DELETE_POST_SUCCESS'

export const SEARCH_POST_SUCCESS = 'SEARCH_POST_SUCCESS'
export const SEARCH_POST_FAIL = 'SEARCH_POST_FAIL'

export const CANCEL_SEARCH_SUCCESS = 'CANCEL_SEARCH_SUCCESS'
export const CANCEL_SEARCH_FAIL = 'CANCEL_SEARCH_FAIL'