# Generated by Django 3.1.3 on 2021-07-24 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='other_post',
        ),
        migrations.RemoveField(
            model_name='score',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='score',
            name='this_post',
        ),
        migrations.AddField(
            model_name='score',
            name='post1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post1', to='form.post'),
        ),
        migrations.AddField(
            model_name='score',
            name='post2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post2', to='form.post'),
        ),
    ]
