# Generated by Django 3.2.5 on 2021-07-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is10000',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='my_column_only',
            field=models.BooleanField(default=False),
        ),
    ]
