# Generated by Django 3.1.3 on 2021-07-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('other_post_id', models.IntegerField()),
                ('score', models.FloatField()),
                ('this_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Selected_choice',
        ),
    ]
