# Generated by Django 3.1.3 on 2021-07-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20210723_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='post_id',
        ),
    ]
