# Generated by Django 3.1.3 on 2021-06-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20210628_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='selected_choices',
            field=models.JSONField(default=list),
        ),
    ]
