# Generated by Django 3.1.3 on 2021-07-24 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0002_auto_20210724_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='owner1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoreowner1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='owner2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoreowner2', to=settings.AUTH_USER_MODEL),
        ),
    ]
