# Generated by Django 3.1.3 on 2021-07-23 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_score_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='other_post_id',
        ),
        migrations.AddField(
            model_name='score',
            name='other_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.post'),
        ),
        migrations.AlterField(
            model_name='score',
            name='this_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='this_post', to='form.post'),
        ),
    ]
