# Generated by Django 3.2.5 on 2021-07-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20210726_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='form.post'),
        ),
    ]
