# Generated by Django 3.2.5 on 2021-07-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_favourite_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='temp_post_id',
            field=models.IntegerField(default=0),
        ),
    ]
