# Generated by Django 3.2.5 on 2021-07-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_favourite_temp_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='form.post'),
        ),
    ]
