export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS'
export const GET_FORM_FAIL = 'GET_FORM_FAIL'

export const LOADING = 'LOADING'
export const RESET_LOADING = 'RESET_LOADING'

export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS'
export const GET_QUESTIONS_FAIL = 'GET_QUESTIONS_FAIL'