export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS'
export const GET_QUESTIONS_FAIL = 'GET_QUESTIONS_FAIL'

export const FORM_LOADING = 'FORM_LOADING'
export const RESET_FORM_LOADING = 'RESET_FORM_LOADING'