export const GET_ROOM_LIST_SUCCESS = 'GET_ROOM_LIST_SUCCESS'
export const GET_ROOM_LIST_FAIL = 'GET_ROOM_LIST_FAIL'

export const CHECK_CHAT_HISTORY_SUCCESS = 'CHECK_CHAT_HISTORY_SUCCESS'
export const CHECK_CHAT_HISTORY_FAIL = 'CHECK_CHAT_HISTORY_FAIL'

export const GET_ROOM_DETAIL_SUCCESS = 'GET_ROOM_DETAIL_SUCCESS'
export const GET_ROOM_DETAIL_FAIL = 'GET_ROOM_DETAIL_FAIL'

export const POST_ROOM_LIST_SUCCESS = 'POST_ROOM_LIST_SUCCESS'
export const POST_ROOM_LIST_FAIL = 'POST_ROOM_LIST_FAIL'

export const EDIT_MSG_SUCCESS = 'EDIT_MSG_SUCCESS'
export const EDIT_MSG_FAIL = 'EDIT_MSG_FAIL'

export const SET_CHAT_USER = 'SET_CHAT_USER'

export const RESET_CHAT_HISTORY = 'RESET_CHAT_HISTORY'
