export const GET_ROOM_LIST_SUCCESS = 'GET_ROOM_LIST_SUCCESS'
export const GET_ROOM_LIST_FAIL = 'GET_ROOM_LIST_FAIL'

export const POST_ROOM_LIST_SUCCESS = 'POST_ROOM_LIST_SUCCESS'
export const POST_ROOM_LIST_FAIL = 'POST_ROOM_LIST_FAIL'

