# Generated by Django 3.1.3 on 2021-07-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_date_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='date_modified',
        ),
    ]
