# Generated by Django 3.1.3 on 2021-07-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.TextField(default=''),
        ),
    ]
