# Generated by Django 3.1.3 on 2021-07-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_owner_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
