# Generated by Django 3.1.3 on 2021-07-17 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_auto_20210717_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='owner_obj',
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
