# Generated by Django 3.1.3 on 2021-07-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210717_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='owner',
        ),
    ]
