# Generated by Django 3.1.3 on 2021-07-17 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0011_auto_20210717_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='owner1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='user1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='user2',
            field=models.IntegerField(default=0),
        ),
    ]
