# Generated by Django 3.1.3 on 2021-07-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20210717_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='owner2',
        ),
    ]
