# Generated by Django 3.1.3 on 2021-07-20 04:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_message_hasread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 7, 20, 4, 21, 22, 99412, tzinfo=utc)),
        ),
    ]
