# Generated by Django 3.1.3 on 2021-07-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourites',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
