# Generated by Django 3.1.3 on 2021-07-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='justRegistered',
            field=models.BooleanField(default=False),
        ),
    ]
