# Generated by Django 3.2.5 on 2021-07-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_light_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='light_theme',
            field=models.BooleanField(default=True),
        ),
    ]
