# Generated by Django 3.1.3 on 2021-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210628_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_pic.jpg', null=True, upload_to='build/static/media'),
        ),
    ]
