# Generated by Django 3.1.3 on 2021-07-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_justregistered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='justRegistered',
        ),
        migrations.AddField(
            model_name='customuser',
            name='just_registered',
            field=models.BooleanField(default=False),
        ),
    ]
