# Generated by Django 3.2.5 on 2021-07-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='theme',
            new_name='light_theme',
        ),
    ]
