# Generated by Django 3.1.3 on 2021-07-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210722_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='just_registered',
            field=models.BooleanField(default=True),
        ),
    ]
