export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const ACTIVATE_SUCCESS = 'ACTIVATE_SUCCESS'
export const ACTIVATE_FAIL = 'ACTIVATE_FAIL'

export const RESEND_ACTIVATION_EMAIL_SUCCESS = 'RESEND_ACTIVATION_EMAIL_SUCCESS'
export const RESEND_ACTIVATION_EMAIL_FAIL = 'RESEND_ACTIVATION_EMAIL_FAIL'

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const CHECK_AUTHENTICATION_SUCCESS = 'CHECK_AUTHENTICATION_SUCCESS'
export const CHECK_AUTHENTICATION_FAIL = 'CHECK_AUTHENTICATION_FAIL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT = 'LOGOUT'

export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL'

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS'
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL'

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'

export const AUTH_LOADING = 'AUTH_LOADING'
export const RESET_AUTH_LOADING = 'RESET_AUTH_LOADING'

export const PROFILE_LOADING = 'PROFILE_LOADING'

export const RESET_AUTH_ERROR_MSG = 'RESET_AUTH_ERROR_MSG'

export const RESET_CHANGE_PASSWORD_SUCCESS = 'RESET_CHANGE_PASSWORD_SUCCESS'
export const RESET_EDIT_BIO_SUCCESS = 'RESET_EDIT_BIO_SUCCESS'
export const RESET_EDIT_FAVOURITES_SUCCESS = 'RESET_EDIT_FAVOURITES_SUCCESS'

export const CHANGE_PROFILE_PIC_SUCCESS = 'CHANGE_PROFILE_PIC_SUCCESS'
export const CHANGE_PROFILE_PIC_FAIL = 'CHANGE_PROFILE_PIC_FAIL'

export const EDIT_BIO_SUCCESS = 'EDIT_BIO_SUCCESS'
export const EDIT_BIO_FAIL = 'EDIT_BIO_FAIL'

export const EDIT_FAVOURITES_SUCCESS = 'EDIT_FAVOURITES_SUCCESS'
export const EDIT_FAVOURITES_FAIL = 'EDIT_FAVOURITES_FAIL'

export const SET_PREV_PATH = 'SET_PREV_PATH'
