export const CREATE_FAVOURITE_SUCCESS = 'CREATE_FAVOURITE_SUCCESS'
export const CREATE_FAVOURITE_FAIL = 'CREATE_FAVOURITE_FAIL'

export const DELETE_FAVOURITE_SUCCESS = 'DELETE_FAVOURITE_SUCCESS'
export const DELETE_FAVOURITE_FAIL = 'DELETE_FAVOURITE_FAIL'

export const RESET_CREATE_FAVOURTIE_SUCCESS = 'RESET_CREATE_FAVOURTIE_SUCCESS'
export const RESET_DELETE_FAVOURTIE_SUCCESS = 'RESET_DELETE_FAVOURTIE_SUCCESS'