export const GET_SCORE_LIST_SUCCESS = 'GET_SCORE_LIST_SUCCESS'
export const GET_SCORE_LIST_FAIL = 'GET_SCORE_LIST_FAIL'

export const GET_SCORE_DETAIL_SUCCESS = 'GET_SCORE_DETAIL_SUCCESS'
export const GET_SCORE_DETAIL_FAIL = 'GET_SCORE_DETAIL_FAIL'

export const CREATE_SCORE_SUCCESS = 'CREATE_SCORE_SUCCESS'
export const CREATE_SCORE_FAIL = 'CREATE_SCORE_FAIL'

export const EDIT_SCORE_SUCCESS = 'EDIT_SCORE_SUCCESS'
export const EDIT_SCORE_FAIL = 'EDIT_SCORE_FAIL'

export const SCORE_LOADING = 'SCORE_LOADING'

export const RESET_GET_SCORE_LIST_SUCCESS = 'RESET_GET_SCORE_LIST_SUCCESS'