export const CREATE_SCORE_SUCCESS = 'CREATE_SCORE_SUCCESS'
export const CREATE_SCORE_FAIL = 'CREATE_SCORE_FAIL'

export const EDIT_SCORE_SUCCESS = 'EDIT_SCORE_SUCCESS'
export const EDIT_SCORE_FAIL = 'EDIT_SCORE_FAIL'